### ISSUE TITLE
Use ember-cli-compass-compiler to compile Sass in addons?

### ISSUE THREAD

**Issue by lolmaus** [quaertym/ember-cli-compass-compiler#47]
Hi!

Currently, `broccoli-sass` is the standard de-facto for compiling addon styles.

I wish addon creators could make the `broccoli-sass` dependency optional, letting users choose which preprocessor to use.

Can `ember-cli-compass-compiler` compile addon styles? How?

**Comment by quaertym** [comment]
Please link a addon that uses `broccoli-sass`, I will take a look at it.

**Comment by lolmaus** [comment]
https://github.com/Blooie/ember-cli-notifications

**Comment by lolmaus** [comment]
Also keep this in mind: https://github.com/ember-cli/ember-cli/issues/2363

**Comment by shaunc** [comment]
having problems with https://github.com/yapplabs/ember-modal-dialog

**Comment by quaertym** [comment]
@stefanpenner Can you help us here? Can addon styles be compiled with `ember-cli-compass-compiler` instead of `broccoli-sass`? Or addon decides its preprocessor?

**Comment by AndrewJo** [comment]
With recent Ember CLI versions (I'm current on 1.13.x), I believe `ember-cli-sass` is the package to look at for compiling SASS instead of `broccoli-sass`. 

However, I looked into this and upon analyzing the source code, realized that there's a bug in https://github.com/quaertym/ember-cli-compass-compiler/blob/master/index.js#L40:
```javascript
var inputTrees = [inputPath];
```

Should really be replaced with:
```javascript
var inputTrees = [tree];
```

Otherwise, you will get an error like this when running `ember build` to build an addon that depends on `ember-cli-compass-compiler`:
```
Build failed.
ENOENT: no such file or directory, lstat ''
Error: ENOENT: no such file or directory, lstat ''
```

Other Ember CLI preprocessor addons already do this:

- [ember-cli-sass:index.js (line 16)](https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L16)
- [ember-cli-less:index.js (line 28)](https://github.com/gdub22/ember-cli-less/blob/master/index.js#L28)

I'll submit a PR that fixes this. There's also an issue of passing compass options for addons which I'll report separately.

**Comment by AndrewJo** [comment]
@quaertym: I've managed to fix it without modifying a single line of code `broccoli-compass-compiler`. I must say, it was a fun problem to solve! :grin:

**Comment by quaertym** [comment]
@AndrewJo :clap: :clap: congratulations, I will review and merge ASAP.
